#!/usr/bin/env bash
# Displays username, user id and home directory for each line of /etc/passwd.

in="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d':' --fields=1,3,6
done < "$in"
