#!/usr/bin/env bash
#Displays the time for 12 hours and 59 minutes
#Display hours from 0 to 12
#Display minutes from 1 to 59

i=0

while [ $i -lt 12 ]
do
	echo "Hour: $i"
	j=1
	while [ $j -le 59 ]
	do
		echo "$j"
		(( j++ ))
	done
	(( i++ ))
done
