#!/usr/bin/env bash

#Displays informaton about the file "school".

if [ -e "school" ]
then
	echo "school file exists"
	if [ -s "school" ]
	then
		echo "shcool file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "school" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
